
name: Copiar app del último release y actualizar AppSourceCop.json

on:
    workflow_dispatch:

    workflow_run:
      workflows: " Create release"  # Nombre exacto del primer flujo de trabajo
      types:
        - completed

env:
    DEST_DIR_APP: ./Verifactu/.alpackages  # Definir rutas de acceso a los archivos
    DEST_DIR_JSON: ./Verifactu
    GITHUB_TOKEN: ${{ secrets.GHTOKEN_AMS }}

jobs:
  actualizar-release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}  # Ejecutar si es manual o si el primer flujo tiene éxito
    outputs:
      pr_number: ${{ steps.cpr.outputs.pull-request-number }}

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Configurar identidad del bot para commits
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Obtener último release
      id: get_release
      
      shell: bash
      run: |
          echo "Url: https://api.github.com/repos/${{ github.repository }}/releases/latest"
          release=$(curl -H "Authorization: Bearer ${{ secrets.GHTOKEN_AMS }}" \
                        -H "Accept: application/vnd.github.v3+json" \
                        https://api.github.com/repos/${{ github.repository }}/releases/latest)
          echo "$release"
          echo "-----------"
                    
          count=$(echo "$release" | jq '.assets | length')
          echo "Nº de artefactos: $count"
          rm -rf $DEST_DIR_APP/*  # Eliminar el contenido de la carpeta .alpackages
          for i in $(seq 0 $((count - 1))); do
            name=$(echo "$release" | jq -r ".assets[$i].name")
            echo "$name"
            url=$(echo "$release" | jq -r ".assets[$i].url")
            echo "$url"
            
            if [[ "$name" != *"TestApps"* ]]; then
              version=$(echo "$name" | grep -oP '(?<=-)[^-]+(?=\.zip)')
              if [[ -n "$version" ]]; then
                echo "Versión encontrada: $version"
              fi
              echo "Descargando $name"
              wget --header "Authorization: Bearer ${{ secrets.GHTOKEN_AMS }}" --header "Accept: application/octet-stream" $url -O temp.zip
              echo "Contenido de temp.zip:"
              unzip -l temp.zip
              unzip -o temp.zip -d $DEST_DIR_APP
              rm temp.zip
            else
              echo "El archivo $name contiene 'TestApps' y no será descargado."
            fi
          done

          if [[ -z "$version" ]]; then
              echo "No se ha encontrado la versión."
          else
              jq --arg version "$version" '.version = $version' $DEST_DIR_JSON/AppSourceCop.json > $DEST_DIR_JSON/AppSourceCop.tmp && mv $DEST_DIR_JSON/AppSourceCop.tmp $DEST_DIR_JSON/AppSourceCop.json
              echo "El fichero AppSourceCop.json ha sido actualizado con la versión: $version"
          fi

    - name: Incorporar cambios
      run: |
          echo 'Incorporar .app:'
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -f $DEST_DIR_APP/*.app
          git add -f $DEST_DIR_JSON

    - name: Crear Pull Request
      id: cpr  # Identificador para utilizar la salida en pasos siguientes
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GHTOKEN_AMS }}
        title: "Actualizar app última versión"
        body: "Este Pull Request incorpora los archivos .app de la última versión para tomarlos como referencia."
        
    - name: Guardar el nº del PR
      run: echo "PR_NUMBER=${{ steps.cpr.outputs.pull-request-number }}" >> $GITHUB_ENV

    - name: Habilitar Pull Request Automerge
      if: steps.cpr.outputs.pull-request-operation == 'created'
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        token: ${{ secrets.GHTOKEN_AMS }}
        pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
        merge-method: squash

  Auto-aprobacion:
    runs-on: ubuntu-latest
    needs: actualizar-release
    permissions: 
      pull-requests: write
    steps: 
      - name: Obtener el nº del PR
        run: |
          echo "Número: ${{ needs.actualizar-release.outputs.pr_number }}"

      - name: Auto-aprobar el pull request
        uses: hmarr/auto-approve-action@v3
        with:
          review-message: "Autoaprobado"
          pull-request-number: ${{ needs.actualizar-release.outputs.pr_number }}
          github-token: ${{ secrets.GHTOKEN_APPSOURCECOP }}
          

    
